defaults:
  - _self_
  - augmentations: aug_1_simclr_cifar.yaml
  - wandb: _private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

###############
# job name
name: "" # --- job name ---
name_kwargs:
  add_method: True
  add_batch_size: True
  # For simplex loss
  add_k: False
  add_p: False
  add_lamb: True 
  # For simlcr loss
  add_temperature: False # round(temperature*100)

###############
# loss
method: "simplex" # Select the loss function: "simplex", "simclr", "barlow_twins"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 2048
  # For simplex
  p: 2
  k: 45000
  lamb: 5
  unimodal: False
  rectify_large_neg_sim: False
  rectify_small_neg_sim: False
  # For simclr
  temperature: 0.1
  # For barlow_twins
  scale_loss: 0.1

###############
# add additional simplex loss
add_simplex_loss:
  enabled: False
  weight: 1.0
  p: 2
  k: 45000
  rectify_small_neg_sim: False

###############
# model and optimizer
backbone:
  name: "resnet18" # --- backbone architecture ---
optimizer:
  name: "lars" # Select the optimizer: "sgd", "lars", "adam", "adamw"
  batch_size: 64 # 32, 64, 128, 256, 512
  lr: 0.075
  lr_method:  "square_root"
  weight_decay: 1e-6
  classifier_lr: 0.1
scheduler:
  name: "warmup_cosine"
max_epochs: 400 # adjust based on your experiment (200 400 1000)

###############
# data
data:
  dataset: cifar100
  train_path: "/data/files/torchvision"
  val_path: "/data/files/torchvision"
  format: "image_folder"
  num_workers: 2

###############
# evaluation in batch
evaluate_batch:
 enable: False
 type: "all"
 skip_before_optm: False

###############
# save and resume
checkpoint:
  enabled: True
  dir: "trained_models" 
  frequency: 50
auto_resume:
  enabled: True

###############
# gpu options
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 32-true
