defaults:
  - _self_
  - wandb: _private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

# seed: 10
name: "linear-probing" # job name
pretrained_feature_extractor:
backbone:
  name: "resnet18"
pretrain_method: "simplex"
data:
  dataset: cifar100
  train_path: "/data/files/torchvision"
  val_path: "/data/files/torchvision"
  format: "image_folder"
  num_workers: 2
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.1
  weight_decay: 1e-4   # changed
scheduler:
  name: "linear"
  warmup_epochs: 0
  # lr_decay_steps: [60, 80]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 50
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 200
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 32-true

