defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

# seed: 10
name: "" # job name
pretrained_feature_extractor: # --- path where we saved the checkpoints ---
backbone:
  name: "resnet18"
pretrain_method: "simclr"
data:
  dataset: cifar10   # cifar10, cifar100
  train_path: # --- path to training data ---
  val_path: # --- path to validation data ---
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.1
  weight_decay: 0
scheduler:
  name: "warmup_cosine"
  warmup_epochs: 0
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 50
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 200
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed

