defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "simclr-linear" # job name
pretrained_feature_extractor: /home/sehee0706/simplex/trained_models/simplex/95sr1xp7/simplex-cifar100-95sr1xp7-ep=390.ckpt # --- trained ckpt path ---
backbone:
  name: "resnet18"
pretrain_method: "barlow"
data:
  dataset: cifar10
  train_path: "/data/files/torchvision"
  val_path: "/data/files/torchvision"
  format: "image_folder"
  num_workers: 2
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.3
  weight_decay: 1e-5
scheduler:
  name: "step"
  lr_decay_steps: [60, 80]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 5
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed

