defaults:
  - _self_
  - augmentations: imagenet.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

wandb:
  enabled: True
  entity: # --- username ---
  project: "vrn"
  offline: false

###############
name: ""   # experiment name
pretrained_feature_extractor: # --- path where we saved the checkpoints ---
pretrain_method: "simclr"

###############
# backbone and optimizer
backbone:
  name: "resnet50"
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.1
  weight_decay: 0
scheduler:
  name: "warmup_cosine"
  warmup_epochs: 0
max_epochs: 200

###############
# data
data:
  dataset: imagenet100
  train_path: # --- path to training data ---
  val_path: # --- path to validation data ---
  format: "image_folder"
  num_workers: 4

###############
# save and resume
checkpoint:
  enabled: True
  dir: # --- path to save checkpoints ---
  frequency: 50
auto_resume:
  enabled: False

###############
# gpu options
devices: [0]   # --- specify GPU devices ---
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed
