defaults:
  - _self_
  - augmentations: # --- your augmentation config file ---
  - wandb: # --- your WandB config file ---
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

###############
# job name
name: # --- job name ---
name_kwargs:
  add_method: Ture
  add_batch_size: Ture
  # For simplex loss
  add_k: False
  add_p: False # round(p*100)
  add_lamb: False # round(lamb*100)
  # For simlcr loss
  add_temperature: False # round(temperature*100)

###############
# loss
method: # Select the loss function: "simplex", "simclr", "barlow_twins"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 2048
  # For simplex
  p: 2
  k: 45000
  lamb: 1.0
  unimodal: True
  rectify_large_neg_sim: False
  rectify_small_neg_sim: False
  # For simclr
  temperature: 0.07
  # For barlow_twins
  scale_loss: 0.1

###############
# add additional simplex loss
add_simplex_loss:
  enabled: True
  weight: 1.0
  p: 2
  k: 45000
  rectify_small_neg_sim: False

###############
# model and optimizer
backbone:
  name: # --- backbone architecture ---
optimizer:
  name:  # Select the optimizer: "sgd", "lars", "adam", "adamw"
  batch_size: 64 # adjust based on your experiment (32, 64, 128, 256 512)
  lr: 0.3
  weight_decay: 1e-4
  classifier_lr: 0.1
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
max_epochs: 1000 # adjust based on your experiment (200 400 1000)

###############
# data
data:
  dataset: cifar100
  train_path: # --- path to your training data ---
  val_path: # --- path to your validation data ---
  format: "image_folder"
  num_workers: 2

###############
# evaluation in batch
evaluate_batch:
 enable: True
 type: "all"
 skip_before_optm: False

###############
# save and resume
checkpoint:
  enabled: True
  dir: # --- directory to save checkpoints ---
  frequency: 50
auto_resume:
  enabled: False

###############
# gpu options
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 32-true