defaults:
  - _self_
  - augmentations: aug_0.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "simplex-cifar100" # job name
method: "simplex"
backbone:
  name: "resnet50"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 2048
  p: 2
  k: 45000
  lamb: 1.0
  use_relu: False
  # rectify_small_neg_sim: False
  # rectify_small_neg_sim: False
data:
  dataset: cifar100
  train_path: "/data/files/torchvision"
  val_path: "/data/files/torchvision"
  format: "image_folder"
  num_workers: 2
optimizer:
  name: "lars"
  batch_size: 64 # 32, 64, 128, 256 512
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 50
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 1000 # 200 400 1000
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 32-true